<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'phpDocumentor\\Reflection\\' => array($vendorDir . '/phpdocumentor/reflection-common/src', $vendorDir . '/phpdocumentor/reflection-docblock/src', $vendorDir . '/phpdocumentor/type-resolver/src'),
    'Webmozart\\Assert\\' => array($vendorDir . '/webmozart/assert/src'),
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
<<<<<<< HEAD
    'Svg\\' => array($vendorDir . '/phenx/php-svg-lib/src/Svg'),
=======
>>>>>>> 03a274e78eec7419183865d8b05928751910e203
    'Stripe\\' => array($vendorDir . '/stripe/stripe-php/lib'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src/Prophecy'),
    'Laminas\\ZendFrameworkBridge\\' => array($vendorDir . '/laminas/laminas-zendframework-bridge/src'),
    'Laminas\\Escaper\\' => array($vendorDir . '/laminas/laminas-escaper/src'),
    'Kint\\' => array($vendorDir . '/kint-php/kint/src'),
<<<<<<< HEAD
    'FontLib\\' => array($vendorDir . '/phenx/php-font-lib/src/FontLib'),
    'Dompdf\\' => array($vendorDir . '/dompdf/dompdf/src'),
=======
>>>>>>> 03a274e78eec7419183865d8b05928751910e203
    'Doctrine\\Instantiator\\' => array($vendorDir . '/doctrine/instantiator/src/Doctrine/Instantiator'),
    'DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
    'CodeIgniter\\' => array($baseDir . '/system'),
);
