<?php

// autoload_real.php @generated by Composer

<<<<<<< HEAD
class ComposerAutoloaderInit6a9e130c17f29608f0171431fe6a8f5c
=======
class ComposerAutoloaderInitd926f4cf155fbec5fe384839c8aca936
>>>>>>> 03a274e78eec7419183865d8b05928751910e203
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

<<<<<<< HEAD
    /**
     * @return \Composer\Autoload\ClassLoader
     */
=======
>>>>>>> 03a274e78eec7419183865d8b05928751910e203
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

<<<<<<< HEAD
        spl_autoload_register(array('ComposerAutoloaderInit6a9e130c17f29608f0171431fe6a8f5c', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInit6a9e130c17f29608f0171431fe6a8f5c', 'loadClassLoader'));
=======
        spl_autoload_register(array('ComposerAutoloaderInitd926f4cf155fbec5fe384839c8aca936', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInitd926f4cf155fbec5fe384839c8aca936', 'loadClassLoader'));
>>>>>>> 03a274e78eec7419183865d8b05928751910e203

        $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION') && (!function_exists('zend_loader_file_encoded') || !zend_loader_file_encoded());
        if ($useStaticLoader) {
            require_once __DIR__ . '/autoload_static.php';

<<<<<<< HEAD
            call_user_func(\Composer\Autoload\ComposerStaticInit6a9e130c17f29608f0171431fe6a8f5c::getInitializer($loader));
=======
            call_user_func(\Composer\Autoload\ComposerStaticInitd926f4cf155fbec5fe384839c8aca936::getInitializer($loader));
>>>>>>> 03a274e78eec7419183865d8b05928751910e203
        } else {
            $map = require __DIR__ . '/autoload_namespaces.php';
            foreach ($map as $namespace => $path) {
                $loader->set($namespace, $path);
            }

            $map = require __DIR__ . '/autoload_psr4.php';
            foreach ($map as $namespace => $path) {
                $loader->setPsr4($namespace, $path);
            }

            $classMap = require __DIR__ . '/autoload_classmap.php';
            if ($classMap) {
                $loader->addClassMap($classMap);
            }
        }

        $loader->register(true);

        if ($useStaticLoader) {
<<<<<<< HEAD
            $includeFiles = Composer\Autoload\ComposerStaticInit6a9e130c17f29608f0171431fe6a8f5c::$files;
=======
            $includeFiles = Composer\Autoload\ComposerStaticInitd926f4cf155fbec5fe384839c8aca936::$files;
>>>>>>> 03a274e78eec7419183865d8b05928751910e203
        } else {
            $includeFiles = require __DIR__ . '/autoload_files.php';
        }
        foreach ($includeFiles as $fileIdentifier => $file) {
<<<<<<< HEAD
            composerRequire6a9e130c17f29608f0171431fe6a8f5c($fileIdentifier, $file);
=======
            composerRequired926f4cf155fbec5fe384839c8aca936($fileIdentifier, $file);
>>>>>>> 03a274e78eec7419183865d8b05928751910e203
        }

        return $loader;
    }
}

<<<<<<< HEAD
function composerRequire6a9e130c17f29608f0171431fe6a8f5c($fileIdentifier, $file)
=======
function composerRequired926f4cf155fbec5fe384839c8aca936($fileIdentifier, $file)
>>>>>>> 03a274e78eec7419183865d8b05928751910e203
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        require $file;

        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
    }
}
